# CI Nivel 4

name: 'Inspection'

on: workflow_dispatch
jobs:
  #descriçao
  inspection:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    #passo a passo
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Padronização de código (Lint)
        run: yarn lint

  unit:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [inspection]

    #passo a passo
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependencias
        run: yarn
      - name: Testes de unidade
        run: yarn run test

  #descriçao
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [unit]

    #passo a passo
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Rodando aplicacao
        run: yarn start &

      - name: Instalando Playwright
        run: yarn playwright install
      - name: Rodando testes e2e-tests
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000/'

        # disponibilizando relatorio (artefato)
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-E2E
          path: ./playwright-report

  deploy:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [e2e-tests]
    steps:
      - name: Deploy
        run: echo "Step deploy"
